from __future__ import annotations

from pathlib import Path

import pytest

from cfg.core.errors import CfgError
from cfg.render.generated import (
    render_repo_generated_template_writes,
    render_template_write_to_string,
    resolve_generated_targets,
)


def _write(p: Path, text: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text.lstrip(), encoding="utf-8")


def test_resolve_generated_targets_detects_conflicts(tmp_path: Path) -> None:
    cfg_root = tmp_path
    _write(
        cfg_root / "features" / "repo" / "a" / "feature.toml",
        """
        schema_version = 1
        requires = []
        conflicts = []
        generated = ["x.txt"]
        """,
    )
    _write(
        cfg_root / "features" / "repo" / "b" / "feature.toml",
        """
        schema_version = 1
        requires = []
        conflicts = []
        generated = ["x.txt"]
        """,
    )

    with pytest.raises(CfgError, match="Generated artifact conflict"):
        resolve_generated_targets(cfg_root=cfg_root, enabled_owner_ids=["repo/feature/a", "repo/feature/b"])


def test_render_repo_generated_template_collects_fragments(tmp_path: Path) -> None:
    cfg_root = tmp_path

    # Feature providing the generated output + template.
    _write(
        cfg_root / "features" / "repo" / "pre-commit-jinja-base" / "feature.toml",
        """
        schema_version = 1
        requires = []
        conflicts = []
        generated = [".pre-commit-config.yaml"]
        """,
    )
    _write(
        cfg_root
        / "features"
        / "repo"
        / "pre-commit-jinja-base"
        / "render"
        / "templates"
        / ".pre-commit-config.yaml.j2",
        """
        # AUTOGENERATED
        {% for f in fragment_files -%}
        # - {{ f.rel_to_cfg_root }}
        {% endfor %}
        repos:
        {% for f in fragments.repos -%}
        {{ f.content | indent(2, true) }}
        {% endfor %}
        """,
    )

    # Two enabled owners contribute fragments for `.pre-commit-config.yaml`.
    _write(
        cfg_root / "repos" / "owner" / "repo" / "cfg.toml",
        """
        id = "owner/repo"
        features = []
        """,
    )
    _write(
        cfg_root
        / "repos"
        / "owner"
        / "repo"
        / "render"
        / "fragments"
        / ".pre-commit-config.yaml"
        / "repos"
        / "00.yml",
        """
        - repo: https://example.com/a
          rev: v1
          hooks: [{id: a}]
        """,
    )
    _write(
        cfg_root / "features" / "repo" / "x" / "feature.toml",
        """
        schema_version = 1
        requires = []
        conflicts = []
        generated = []
        """,
    )
    _write(
        cfg_root
        / "features"
        / "repo"
        / "x"
        / "render"
        / "fragments"
        / ".pre-commit-config.yaml"
        / "repos"
        / "10.yml",
        """
        - repo: https://example.com/b
          rev: v2
          hooks: [{id: b}]
        """,
    )

    enabled = ["repo/feature/pre-commit-jinja-base", "repo/owner/repo", "repo/feature/x"]
    writes = render_repo_generated_template_writes(
        cfg_root=cfg_root,
        repo_id="owner/repo",
        enabled_owner_ids=enabled,
        only_rels={Path(".pre-commit-config.yaml")},
    )
    assert len(writes) == 1
    w = writes[0]
    assert w.rel == Path(".pre-commit-config.yaml")
    assert "fragments" in w.data
    assert "fragment_files" in w.data

    rendered = render_template_write_to_string(w)
    assert rendered.startswith("# AUTOGENERATED\n")
    assert "- repo: https://example.com/a" in rendered
    assert "- repo: https://example.com/b" in rendered
    # Header lists fragment sources:
    assert "repos/owner/repo/render/fragments/.pre-commit-config.yaml/repos/00.yml" in rendered
    assert "features/repo/x/render/fragments/.pre-commit-config.yaml/repos/10.yml" in rendered


def test_render_repo_generated_template_requires_source_file(tmp_path: Path) -> None:
    cfg_root = tmp_path
    _write(
        cfg_root / "features" / "repo" / "t" / "feature.toml",
        """
        schema_version = 1
        requires = []
        conflicts = []
        generated = ["hello.txt"]
        """,
    )

    with pytest.raises(CfgError, match="Missing generated template source"):
        render_repo_generated_template_writes(
            cfg_root=cfg_root,
            repo_id="owner/repo",
            enabled_owner_ids=["repo/feature/t"],
            only_rels={Path("hello.txt")},
        )
