from __future__ import annotations

import difflib
from collections.abc import Mapping, Sequence
from pathlib import Path

from cfg.core.errors import CfgError
from cfg.core.ids import OwnerId
from cfg.core.models import RepoSettings
from cfg.core.owners import OwnerManifest
from cfg.render.generated import (
    TemplateWrite,
    render_repo_generated_template_writes,
    render_template_write_to_string,
)
from cfg.repo.git import staged_file_content, staged_paths


def _normalized(content: str) -> str:
    return content.rstrip() + "\n"


def _fragment_rels(write: TemplateWrite) -> list[str]:
    fragments = write.data.get("fragment_files") or []
    return [
        str(fragment.get("rel_to_cfg_root") or "").strip()
        for fragment in fragments
        if str(fragment.get("rel_to_cfg_root") or "").strip()
    ]


def _raise_drift(
    *,
    rel: Path,
    expected: str,
    actual: str | None,
    fragment_rels: Sequence[str],
) -> None:
    actual_text = _normalized(actual) if actual is not None else ""
    diff = "\n".join(
        difflib.unified_diff(
            expected.splitlines(),
            actual_text.splitlines(),
            fromfile=f"expected ({rel.as_posix()} from cfg)",
            tofile=f"actual ({rel.as_posix()} in repo)",
            lineterm="",
        )
    )
    fragments = "\n".join(f"- {path}" for path in fragment_rels) or "(none)"
    missing = "\nThe generated file is missing or staged for deletion.\n" if actual is None else ""
    raise CfgError(
        f"Managed generated file drift detected: `{rel.as_posix()}` was edited directly.\n"
        f"{missing}\n"
        "This file is autogenerated by cfg from these fragment(s):\n"
        f"{fragments}\n\n"
        "Fix by editing the fragment(s), then regenerate:\n"
        "- `cfg repo apply`\n"
        "\n"
        "Diff:\n"
        f"{diff}\n"
    )


def check_generated_files_drift(
    *,
    cfg_root: Path,
    repo_root: Path,
    repo_id: str,
    repo_cfg: RepoSettings,
    enabled_owner_ids: Sequence[OwnerId],
    manifest_index: Mapping[OwnerId, OwnerManifest] | None = None,
    staged: bool,
) -> None:
    """Check every configured generated output against one canonical render."""
    writes = render_repo_generated_template_writes(
        cfg_root=cfg_root,
        repo_id=repo_id,
        enabled_owner_ids=enabled_owner_ids,
        manifest_index=manifest_index,
        path_provider_overrides=repo_cfg.path_provider_overrides,
    )
    staged_rels = set(staged_paths(repo_root)) if staged else set()

    for write in writes:
        rel = write.rel
        if staged and rel.as_posix() not in staged_rels:
            continue

        expected = _normalized(render_template_write_to_string(write))
        if staged:
            actual = staged_file_content(repo_root, rel.as_posix())
        else:
            target = repo_root / rel
            actual = target.read_text(encoding="utf-8") if target.is_file() else None

        if actual is not None and _normalized(actual) == expected:
            continue
        _raise_drift(
            rel=rel,
            expected=expected,
            actual=actual,
            fragment_rels=_fragment_rels(write),
        )
