from __future__ import annotations

from pathlib import Path

from cfg.core.errors import CfgError
from cfg.core.models import RepoSettings
from cfg.render.generated import render_repo_generated_template_writes, render_template_write_to_string
from cfg.repo.git import staged_file_content, staged_paths


def _expected_generated_content(
    *,
    cfg_root: Path,
    repo_id: str,
    enabled_owner_ids: list[str],
    path_provider_overrides: dict[str, str] | None,
    rel: Path,
) -> tuple[str, list[str]]:
    writes = render_repo_generated_template_writes(
        cfg_root=cfg_root,
        repo_id=repo_id,
        enabled_owner_ids=enabled_owner_ids,
        path_provider_overrides=path_provider_overrides,
        only_rels={rel},
    )
    if not writes:
        return "", []
    if len(writes) != 1:
        raise CfgError(f"Expected exactly one generated write for {rel.as_posix()}, got: {len(writes)}")
    rendered = render_template_write_to_string(writes[0]).rstrip() + "\n"
    frag_files = writes[0].data.get("fragment_files") or []
    rels = [
        str(f.get("rel_to_cfg_root") or "").strip()
        for f in frag_files
        if str(f.get("rel_to_cfg_root") or "").strip()
    ]
    return rendered, rels


def check_generated_file_drift(
    *,
    cfg_root: Path,
    repo_root: Path,
    repo_id: str,
    repo_cfg: RepoSettings,
    enabled_owner_ids: list[str],
    staged: bool,
    rel: Path,
) -> None:
    """
    Drift check for a generated file.

    The write path and this drift check render the same Jinja2 template to a
    string, so drift comparison uses the same content as apply.
    """
    # Only check when staged if requested.
    if staged and str(rel) not in staged_paths(repo_root):
        return

    expected, fragment_rels = _expected_generated_content(
        cfg_root=cfg_root,
        repo_id=repo_id,
        enabled_owner_ids=enabled_owner_ids,
        path_provider_overrides=repo_cfg.path_provider_overrides,
        rel=rel,
    )
    if not expected:
        return

    if staged:
        actual_raw = staged_file_content(repo_root, str(rel))
        if actual_raw is None:
            return
        actual = actual_raw.rstrip() + "\n"
    else:
        p = repo_root / rel
        actual = (p.read_text(encoding="utf-8").rstrip() + "\n") if p.is_file() else None
        if actual is None:
            return

    if actual == expected:
        return

    import difflib

    frags = "\n".join(f"- {p}" for p in fragment_rels) or "(none)"
    diff = "\n".join(
        difflib.unified_diff(
            expected.splitlines(),
            actual.splitlines(),
            fromfile=f"expected ({rel.as_posix()} from cfg)",
            tofile=f"actual ({rel.as_posix()} in repo)",
            lineterm="",
        )
    )
    raise CfgError(
        f"Managed generated file drift detected: `{rel.as_posix()}` was edited directly.\n\n"
        "This file is autogenerated by cfg from these fragment(s):\n"
        f"{frags}\n\n"
        "Fix by editing the fragment(s), then regenerate:\n"
        "- `cfg repo apply`\n"
        "\n"
        "Diff:\n"
        f"{diff}\n"
    )


def check_repo_precommit_drift(
    *,
    cfg_root: Path,
    repo_root: Path,
    repo_id: str,
    repo_cfg: RepoSettings,
    enabled_owner_ids: list[str],
    staged: bool,
) -> None:
    """
    Back-compat wrapper for older callers.
    """
    from cfg.repo.precommit import PRECOMMIT_PATH

    check_generated_file_drift(
        cfg_root=cfg_root,
        repo_root=repo_root,
        repo_id=repo_id,
        repo_cfg=repo_cfg,
        enabled_owner_ids=enabled_owner_ids,
        staged=staged,
        rel=PRECOMMIT_PATH,
    )
